/**
 * Type definitions for filter presets
 */

/**
 * Sort field configuration
 */
export interface SortField {
  field: string;
  direction: 'asc' | 'desc';
}

/**
 * Header filters for transaction search
 */
export interface HeaderFilters {
  primaryGrantName?: string;
  primaryBudgetItemName?: string;
  account?: string;
  department?: string;
  supplier?: string;
  item?: string;
  description?: string;
  detailDescription?: string;
  memo?: string;
  tags?: string;
  minAmount?: string;
  maxAmount?: string;
  startDate?: string;
  endDate?: string;
  [key: string]: string | undefined; // Allow index signature for dynamic access
}

/**
 * Checkbox filters using Sets
 */
export interface CheckboxFilters {
  allocationStatus: Set<string>;
  account: Set<string>;
  department: Set<string>;
  supplier: Set<string>;
  item: Set<string>;
  primaryGrantName: Set<string>;
  primaryBudgetItemName: Set<string>;
}

/**
 * Budget item filters
 */
export interface BudgetItemFilters {
  statusFilter?: string;
  grantFilter?: string;
  categoryFilter?: string;
}

/**
 * Complete filter configuration
 */
export interface FilterConfiguration {
  headerFilters?: HeaderFilters;
  checkboxFilters?: CheckboxFilters;
  budgetFilters?: BudgetItemFilters;
  sorts?: SortField[];
  transactionSorts?: SortField[];
}

/**
 * Filter preset definition
 */
export interface FilterPreset {
  id: string;
  name: string;
  filters: HeaderFilters | FilterConfiguration;
  sorts: SortField[] | null;
  budgetFilters: BudgetItemFilters | null;
  createdAt?: string;
  updatedAt?: string;
  isDefault?: boolean;
  isAutoGenerated?: boolean;
}

/**
 * Preset validation result
 */
export interface PresetValidation {
  isValid: boolean;
  errors: string[];
}

/**
 * Default preset configuration
 */
export interface DefaultPresetConfig {
  id: string;
  name: string;
  getFilters: () => HeaderFilters;
}

/**
 * Storage constants
 */
export const PRESET_STORAGE_KEY = 'filter-presets-simple';
export const FILTER_STATE_STORAGE_KEY = 'transaction-allocation-filters';

/**
 * Default preset IDs (for easy reference)
 */
export const DEFAULT_PRESET_IDS = {
  THIS_MONTH: 'default-this-month',
  LAST_MONTH: 'default-last-month',
  TWO_MONTHS_AGO: 'default-two-months-ago',
  THREE_MONTHS: 'default-three-months',
} as const;

/**
 * Maximum number of custom presets allowed
 */
export const MAX_CUSTOM_PRESETS = 20;

/**
 * Maximum preset name length
 */
export const MAX_PRESET_NAME_LENGTH = 50;